### ISSUE TITLE
How to get Variable values in FastAGI Script

### ISSUE THREAD

**Issue by phaneendranatha** [gawel/panoramisk#104]
Hello..

How to get Asterisk variables values in FastAGI Script 

Thanks
Bandiphani

**Comment by gawel** [comment]
Hi, read the examples https://github.com/gawel/panoramisk/blob/master/examples/fast_agi_server.py

And please do not use issues for support

**Comment by phaneendranatha** [comment]
Hi gawel,

pls let me know where should I get support ?

need support on getting asterisk variable values 

pprint((await request.send_command('GET VARIABLE UNIQUEID')))
Response printed like below..
{'msg': '', 'result': ('1', 'OK'), 'status_code': 200}

How can I save UNIQUEID value to variable.

**Comment by gawel** [comment]
Have you looked at the example? I've never used fastagi but this line said some variables are in the request headers https://github.com/gawel/panoramisk/blob/master/examples/fast_agi_server.py#L9

Else you should ask your question on stack overfow  or another community support like that
