### ISSUE TITLE
asyncio.start_server no longer needs parameter loop=loop

### ISSUE THREAD

**Issue by vishalvignesh** [gawel/panoramisk#111]
Hi, I'm not exactly sure if I missed a python version requirement somewhere, but in the example files I checked, such as [fast_agi_server.py] and [fast_agi_server_ivr.py], from python version 3.10, asyncio.start_server no longer needs the loop=loop parameter, including it will cause the code to crash and fail to start. 
The server successfully starts after removing the parameter.

**Comment by romkazor** [comment]
Yep, 3.10-3.11 support needed
