### ISSUE TITLE
scripts

### ISSUE THREAD

**Issue by areski** [gawel/panoramisk#20]
Could we provide documentation on https://github.com/gawel/panoramisk/blob/master/panoramisk/scripts.py maybe an example of config file and input yaml file?

maybe we should rename scripts to command.py or console_script.py ?

**Comment by gawel** [comment]
Seems a good idea. I may do that at pyconfr. Except if you want to provide a PR of course :)

**Comment by areski** [comment]
I created a PR for the obvious part, the one on renaming to command.py: https://github.com/gawel/panoramisk/pull/24

but I would love to see a complete example of config.ini as you use it at your end.

**Comment by GMLudo** [comment]
PR merged, I close this issue.

Thanks for your contribution.
