### ISSUE TITLE
connection_class in config

### ISSUE THREAD

**Issue by areski** [gawel/panoramisk#21]
'''connection_class''' is in config but doesn't seem configurable, or I might be missing something?
https://github.com/gawel/panoramisk/blob/master/panoramisk/manager.py#L31

**Comment by GMLudo** [comment]
Never tested, however, it should be configurable if you pass **connection_class** parameter like this:

    manager = Manager(connection_class=Connection) 

Because you have this: https://github.com/gawel/panoramisk/blob/master/panoramisk/manager.py#L37
And this: https://github.com/gawel/panoramisk/blob/master/panoramisk/manager.py#L164

**Comment by gawel** [comment]
Yes, that's the idea. You can override the protocol at a lower level if needed. I think it's always a good idea to provide this to avoid ugly monkey patching.

Maybe we can make it configurable: point to a class in the config file and resolve the name to use it. That's the kind of think I'm doing in irc3: https://github.com/gawel/irc3/blob/master/irc3/utils.py#L263

**Comment by GMLudo** [comment]
At least to me, the actual behaviour it's enough to me.
I've already customized some class with the same mechanism in aiohttp:
https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/client.py#L36

I didn't detect a corner case that could justify a more complex mechanism.

**Comment by areski** [comment]
Thanks for the clarification, it's much appreciated.
