### ISSUE TITLE
Suggestion to rename Connection to AMIProtocol

### ISSUE THREAD

**Issue by areski** [gawel/panoramisk#22]
Ref https://github.com/gawel/panoramisk/blob/master/panoramisk/connection.py
Connection seems misleading to my opinion, where this is actually the Protocol.

**Comment by GMLudo** [comment]
To be honest with you, I did the same reflexion the first time I've contributed to Panoramisk, to be consistent with AsyncIO terminology.
However, at least to me, I don't have a strong opinion to change or not that, as you like guys.
@gawel: Do you see a issue to change that ?
@areski: If you're interested in, you could propose a PR to see the impacts in the source code.

**Comment by gawel** [comment]
Ok for me

**Comment by areski** [comment]
Here a PR so we can start discussing of what are the best options, https://github.com/gawel/panoramisk/pull/23

**Comment by areski** [comment]
I just renamed also connection_class to protocol_factory to follow on https://docs.python.org/3/library/asyncio-eventloop.html#creating-connections

**Comment by GMLudo** [comment]
PR merged, I close this issue.

Thanks for your contribution.
