### ISSUE TITLE
Suggestion: create a simple example using manager.register_event()

### ISSUE THREAD

**Issue by osantana** [gawel/panoramisk#26]
I'm an asyncio "newbie" and really like to see a simple but complete sample of manager.register_event() usage in a "server_forever" loop.

**Comment by GMLudo** [comment]
I'm sorry, no time right now to do that.
Maybe another panoramisk user should propose an example as PR ?

**Comment by osantana** [comment]
I'll try to make it by myself and send a PR. I'm a experienced Python developer but a newbie in asyncio/coroutine related subject and that's why I'm asking for some help here.

(I'm currently reading the asyncio chapter of Fluent Python book to learn how to use it and I could use panoramisk as an exercise :smile:)

**Comment by GMLudo** [comment]
If you are smart enough to handle Asterisk and VoIP in general, AsyncIO and async pattern in general should be considered easy as pie, at least to me ;-)
Good luck in discovery. 
If you aren't enough confident in Asterisk, I recommend you to build first an aiohttp.web daemon with classical HTTP and after WebSockets.
The learning curve will be easier to handle.

**Comment by tannermkerr** [comment]
osantana, I've just submitted a pull request that has an example for you

**Comment by osantana** [comment]
Cool! Thanks @tannermkerr! It'll be very useful on my next project: https://github.com/osantana/ami-push

It's only a project boilerplate that I started yesterday but the main goal is to create a daemon that listen for AMI events and make http request to an specific URL when some specific event type are triggered.

**Comment by tannermkerr** [comment]
no problem glad to help. I was having the same issue as you, while trying to create a custom reporting tool.

**Comment by GMLudo** [comment]
@osantana: good idea with ami-push: Don't hesitate to ping me when it will be done.

@tannermkerr: for custom reporting tool, I recommend you to use CEL: https://wiki.asterisk.org/wiki/pages/viewpage.action?pageId=5242932
https://wiki.asterisk.org/wiki/display/AST/Asterisk+12+CEL+Specification

With that and pgsql connector, you can build a reporting tool without AMI.
However, with AMI, you can receive also CEL events, useful for realtime reporting.

Have a nice day.

**Comment by osantana** [comment]
Hi,

As I promissed follow a link to my project that make http-posts based on events on AMI:

https://github.com/osantana/ami-push

Thanks for panoramisk!

**Comment by GMLudo** [comment]
@osantana it looks promising ;-)
