### ISSUE TITLE
For travis-ci, our tests are always good

### ISSUE THREAD

**Issue by GMLudo** [gawel/panoramisk#32]
Hi @jordanrinke,

`.travis.script` seems to hide errors in our tests for Travis-CI: https://travis-ci.org/gawel/panoramisk/jobs/91225493#L509

Do you have a suggestion to fix that ?

Have a nice day.

**Comment by gawel** [comment]
Adding "set -e" at the beginning of the script should fix the problem

**Comment by jordanrinke** [comment]
I believe gawel is correct. The problem is that the last command in the script is executing properly, so the other errors aren't being captured by travis. The set -e would make it abort instantly with an error instead of continuing.

**Comment by GMLudo** [comment]
Issue fixed with: 22bf18961dc57c42f84374be9f39d2f4691487b8
Thanks for your help.
