### ISSUE TITLE
Some help

### ISSUE THREAD

**Issue by chesstrian** [gawel/panoramisk#33]
Hi guys,

Thanks for this great library. I need to listen to some events in Asterisk Manager Interface and send related info to a client connected via browser, then I'd like to use this library with Django and Websocket, any hint about this respect?.

Thanks in advance.

**Comment by GMLudo** [comment]
Personally, I use on production panoramisk+aiohttp.web: http://aiohttp.readthedocs.org/en/stable/web.html#websockets

I see no problems to use Websockets library instead.
However, if your Django code and Websockets code runs in the same instance daemon, your blocking I/O in Django will block your async code in Websockets.

If you have two daemons it won't be an issue.
