### ISSUE TITLE
Multiple connection when using manager.send_action()

### ISSUE THREAD

**Issue by myelin13** [gawel/panoramisk#34]
Hello, I'm new in python and I want to optimalize my script. Please, is there a way how to use manager.send_action() multiple times in one script without creating multiple connections ?

Depending on queue_status example I create class and I want to in __init__() set up manager and in others methods don't create new manager connection.
e.g. 

    class AmiClient:
    '''
    Initialize manager
    '''
    def __init__(self):
        # Set up connection manager
        self.manager = Manager(loop=asyncio.get_event_loop(),
                  host=self.amiHost,
                  username=self.amiUser,
                  secret=self.amiPass)
        self.foo()

    '''
    Get variable from channel
    '''
    def foo(self):
        loop = asyncio.get_event_loop()
        channels = loop.run_until_complete(self.getChannels())
        variable = loop.run_until_complete(self.getVar(var,channel))
        # another call
        variable2 = loop.run_until_complete(self.getVar(var2,channel))

    '''
    Get all active core channels
    '''
    @asyncio.coroutine
    def getChannels(self):
        yield from self.manager.connect()
        channels = yield from self.manager.send_action({'Action': 'CoreShowChannels'})
        return channels

    '''
    Get variable from channel
    '''
    @asyncio.coroutine
    def getVar(self, var, channel):
        yield from self.manager.connect()
        variable = yield from self.manager.send_action({
            'Action': 'Getvar',
            'Channel': channel,
            'Variable' : var
            })
        if variable.Value:
            return variable.Value
        else:
            return None

Thank you.

**Comment by gawel** [comment]
that's a design problem, not a panoramisk bug. you should get some help somewhere else.
there is may way to do what you want but my recommendation is to not init the manager in your class.

by the way run_until_complete must be used only once. you should `yield from self.getChannels()`

**Comment by GMLudo** [comment]
@gawel: It's me who told him to post here, I'll answer him.

**Comment by myelin13** [comment]
Thank you for help @GMLudo.

**Comment by GMLudo** [comment]
Hi @myelin13,

I'm sorry, I'm very busy.

In your Class, you should have a coroutine method, named 'start', where you can launch: yield from self.manager.connect()

After in your methods, you can call directly: yield from self.manager.send_action

Have a nice day.
