### ISSUE TITLE
Documentation fix : need Login + secret in config + example

### ISSUE THREAD

**Issue by otaf** [gawel/panoramisk#5]
The manager actually connects (Logins) with a user from **config
panoramisk.Manager(**config)[source]

* The documentation does not reflect this
https://panoramisk.readthedocs.org/en/latest/#panoramisk.Manager

My suggestions : 
* As there are no sane defaults for the Login/secret, just mention that a Login/secret is needed and should be accessible from **config

* The ability to use the lib also depends on asterix config to allow connection to TCP or http mode, as explained in https://wiki.asterisk.org/wiki/display/AST/Allow+Manager+Access+via+HTTP.

I suggest updating the basic example from doc by dumping the content of config that contains Login and Secret.

**Comment by GMLudo** [comment]
Hi @otaf,

I think that documentation, or at least examples, are now enough self explanatory to login. Is it ok for you ?
About http mode, it isn't necessary anymore, we use now `AMI` with `tcp` only.
And yes, we should add a `manager.conf` example in documentation.

**Comment by GMLudo** [comment]
Hi @otaf,

I've just added a manager.conf example in our documentation.
It will be available when @gawel pushes that on readthedocs.

Have a nice week-end.
