### ISSUE TITLE
ChanVariable

### ISSUE THREAD

**Issue by romkazor** [gawel/panoramisk#72]
Hello. Is there an easy way to get ChanVariable in panomarisk lib?
In other lib i can use event['ChanVariable']['SomeKey'] but in panomarisk ChanVariables is a list

**Comment by gawel** [comment]
That's because everything become a list if there is more than one header: https://github.com/gawel/panoramisk/blob/master/panoramisk/message.py#L110

Maybe this key should be converted to dict.

What is the content of your list ?

**Comment by romkazor** [comment]
Yes, i can convert it to dict using a delimiter '=' but its very uncomfortable and should be native in the lib.

```
{'AccountCode': '',
 'CallerIDName': '<unknown>',
 'CallerIDNum': '88888888888',
 'ChanVariable': ['CALLFILENAME=out-77777777777-unknown-20181214-165617-1544795777.560',
                  'FROM_DID=',
                  'CHANNEL(hangupsource)=',
                  'DIALSTATUS=',
                  'PREDICTION=',
                  'SIPURI=sip:100@10.10.23.1:5066'],
 'Channel': 'SIP/100-0000011d',
 'ChannelState': '4',
 'ChannelStateDesc': 'Ring',
 'ConnectedLineName': '<unknown>',
 'ConnectedLineNum': '<unknown>',
 'Context': 'macro-dialout-trunk',
 'DestAccountCode': '',
 'DestCallerIDName': '<unknown>',
 'DestCallerIDNum': '77777777777',
 'DestChanVariable': ['CALLFILENAME=out-77777777777-unknown-20181214-165617-1544795777.560',
                      'FROM_DID=',
                      'CHANNEL(hangupsource)=',
                      'DIALSTATUS=',
                      'PREDICTION=',
                      'SIPURI='],
 'DestChannel': 'SIP/operator-88888888888-0000011e',
 'DestChannelState': '0',
 'DestChannelStateDesc': 'Down',
 'DestConnectedLineName': '<unknown>',
 'DestConnectedLineNum': '74959898533',
 'DestContext': 'from-trunk-fix',
 'DestExten': '77777777777',
 'DestLanguage': 'en',
 'DestLinkedid': '1544795777.560',
 'DestPriority': '1',
 'DestUniqueid': '1544795777.561',
 'DialString': 'operator-88888888888/77777777777',
 'Event': 'DialBegin',
 'Exten': 's',
 'Language': 'en',
 'Linkedid': '1544795777.560',
 'Priority': '20',
 'Privilege': 'call,all',
 'Timestamp': '1544795777.560178',
 'Uniqueid': '1544795777.560',
 'content': ''}
```

**Comment by gawel** [comment]
That's what I meant :)

**Comment by gawel** [comment]
Didn't see your PR coming. But this will not work. Some values must be a list (I guess).

Instead I've added a getdict method https://github.com/gawel/panoramisk/commit/84642bab00aecbb061789fc9e8a5d5103e3e9e42 Does that works for you ?

And I don't think we sort keys. It just use a MutableMapping https://github.com/gawel/panoramisk/blob/master/panoramisk/utils.py#L145 Python do dot order mapping keys. In fact the order may vary from a python version to another.

Maybe it's possible to keep track of this order but I'm not sure this is really useful

**Comment by romkazor** [comment]
Ok, thanks, getdict is working properly.
