### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'send' in manager.py line 138 - panoramisk 1.3

### ISSUE THREAD

**Issue by nh-mike** [gawel/panoramisk#74]
Hi,

Please bear in mind that I am quite new to Python, so I may make little to no sense below (read I have much to learn).

When trying to send a command from the Panoramisk Manager, I get the error as per above, referencing to Manager.prototype.send. The applicable part of my code is as below.

```
manager = panoramisk.Manager(
#host, port, username, secret
)

def handle_response(response):
    print(response)

response = manager.send_command('queue show 510')
response.add_done_callback(handle_response)
```

I have tried with and without a manager.connect() directly after declaring my manager object, with no difference found.

Upon getting the aforementioned error, I have looked into the originating file, manager.py, and finding that the indentation of the initial try block in the connection_made function making no sense to me (lines 57 - 56). I believe that they may need to be indented another level, however upon doing this, I find no difference to my own problem.

I do find that when i pprint(self.protocol), it does indeed return None.

I'm not quite sure what more I can do with my limited knowledge, can you provide any suggestions which might help me to resolve this?

Thanks.

**Comment by gawel** [comment]
Your code make no sense at all.

First learn python, then asyncio, then follow the examples: https://github.com/gawel/panoramisk/tree/master/examples

And please, do not use an issue tracker to ask python questions. Use whatever forum instead. Like https://stackoverflow.com/

**Comment by nh-mike** [comment]
Hmmm, I do have much to learn. In the mean time, I can work with the queue status example given. My apologies, I was uncertain whether this was indeed an issue or not, because I could not trace it back anywhere but where mentioned in my question. I'll close this now.

Thank you.
