### ISSUE TITLE
fast_agi send_command can't handle multiple responses from GOSUB

### ISSUE THREAD

**Issue by HansAdema** [gawel/panoramisk#75]
I'm currently playing around with the FastAGI part of this library. I can call many different AGI commands without any problem through the library, but I have some issues with the `GOSUB` command.

Most commands only send one response when they are done. However, `GOSUB` normally sends two responses, a `100 result=0 Trying...` when the command is started and a `200 result=0 Gosub complete` when the command is done. https://github.com/asterisk/asterisk/blob/13.24/apps/app_stack.c#L1224

However, Panoramisk currently doesn't accept either of that behaviour. When running the `GOSUB` command, it does not recognize the `100` status code, and will parse this as an `AGIUnknownError`. https://github.com/gawel/panoramisk/blob/84642bab00aecbb061789fc9e8a5d5103e3e9e42/panoramisk/utils.py#L55

IMO, the way to fix this is to edit `send_command`, check for `100` status codes (or possibly all codes < 200) and if such a response is returned, wait again for the next response and return that instead.

**Comment by gawel** [comment]
I'm not using this but it seems that your proposal make sens.  
It's probably not necessary to handle <200. I guess 100 is the only one for this use case. HTTP 100 is also "Continue".

Feel free to provide a PR
