### ISSUE TITLE
Asterisk 16 no newexten

### ISSUE THREAD

**Issue by highlife22** [gawel/panoramisk#84]
Hello,

In Asterisk 16.2.1~dfsg-1+deb10u1 on debian 10
I cannot detect "Newexten" event, even with '*' i can't have all event.

```python
@manager.register_event('Newexten')
def callback(manager, message):
    if message.Application == "NoOp" and not message.AppData == "":
        print(message.Channel + " : " + message.AppData)
        resultTmp = str(message.AppData).split(" : ")
        thisdict[resultTmp[0]] = resultTmp[1]
```

But on Asterisk 13.14.1~dfsg-2+deb9u4 on debian 9
The same code work

Have you any idea why ?

**Comment by gawel** [comment]
This is not useful :) I meant the ami stream (sorry)

There's an option for that (I totally forgot about it). Try:

```
manager = Manager(..., save_stream='/tmp/log.txt')
```
And paste the revelant part of the log here. Where the missed event is (with a few before/after events if possible).

**Comment by highlife22** [comment]
Here the full log (asterisk 16): https://pastebin.com/2zt0RGw6

```
Event: DialEnd
Privilege: call,all
DestChannel: SIP/outcall-00000004
DestChannelState: 6
DestChannelStateDesc: Up
DestCallerIDNum: <unknown>
DestCallerIDName: <unknown>
DestConnectedLineNum: <unknown>
DestConnectedLineName: <unknown>
DestLanguage: en
DestAccountCode: 
DestContext: default
DestExten: 
DestPriority: 1
DestUniqueid: 1571384330.8
DestLinkedid: 1571384330.8
DialStatus: ANSWER

Response: Success
ActionID: action/340815d1-07e2-4fea-88c0-d6b725c10488/1/2
Ping: Pong
Timestamp: 1571384340.201775

Response: Success
ActionID: action/340815d1-07e2-4fea-88c0-d6b725c10488/1/3
Ping: Pong
Timestamp: 1571384350.212538

Response: Success
ActionID: action/340815d1-07e2-4fea-88c0-d6b725c10488/1/4
Ping: Pong
Timestamp: 1571384360.219510

Response: Success
ActionID: action/340815d1-07e2-4fea-88c0-d6b725c10488/1/5
Ping: Pong
Timestamp: 1571384370.229762

Response: Success
ActionID: action/340815d1-07e2-4fea-88c0-d6b725c10488/1/6
Ping: Pong
Timestamp: 1571384380.237753

Event: SoftHangupRequest
Privilege: call,all
Channel: SIP/outcall-00000004
ChannelState: 6
ChannelStateDesc: Up
CallerIDNum: <unknown>
CallerIDName: <unknown>
ConnectedLineNum: <unknown>
ConnectedLineName: <unknown>
Language: en
AccountCode: 
Context: end
Exten: start
Priority: 3
Uniqueid: 1571384330.8
Linkedid: 1571384330.8
Cause: 16
```

Here the full log (asterisk 13): https://pastebin.com/9eN8Fcx4

I can't see the Event: Newexten in asterisk 16.

Thank you for your time and help

**Comment by gawel** [comment]
So panoramisk can't parse something that does shows up :)

Maybe your user needs more permission to see those events ? I'm not really an asterisk guru so I can't tell. You should ask the asterisk support/team. Let me know.

**Comment by highlife22** [comment]
Thank you, you give me the clue !

It was the right, betwen asterisk 13 and 16 for the event you need more right.
The problems was from my configuration of asterisk not from panoramisk, 

You need to add in /etc/asterisk/manager.conf :
 - dialplan – Receive NewExten and VarSet events. Read-only.

Found the doc here : https://www.voip-info.org/asterisk-manager-api/

Thank you for your time and help keep your good work !

**Comment by ldo** [comment]
Interesting that that voip-info.org page doesn’t list the `all` privilege, which automatically subsumes all the others and which I think is usually what you want. This is documented in the file `configs/samples/manager.conf.sample` in the Asterisk source tree.
