### ISSUE TITLE
how to parse output of actions to json

### ISSUE THREAD

**Issue by starlessboi** [gawel/panoramisk#85]
Hi
is there a way to parse output of panoramisk, to json?
for example the output of set actions commands for extension status is like below:
<Message ActionID='action/7c33f203-d48e-4f6a-8020-b9ff669bf1bd/1/30' Context='default' Exten='9990' Hint='SIP/9990'
	Message='Extension Status' Response='Success' Status='4' StatusText='Unavailable' content=''>
is there a way to get output in json, or a way to parse this to get only as below:
{StatusText : 'Unavailable'}

**Comment by gawel** [comment]
A message is just a subclass of dict https://github.com/gawel/panoramisk/blob/master/panoramisk/message.py

You should be able to `print(json.dumps(dict(message.items()))`
