### ISSUE TITLE
Incomplete AMI Action Response

### ISSUE THREAD

**Issue by lorenzocampanile** [gawel/panoramisk#86]
Hi!

I used your library to make small control systems on PBXs. When the server with Panoramisk and the Asterisk server are close (low latency) there are no problems.

On the other hand, if the two servers are far away (like Finland my server, and Brazil Asterisk server), communication presents difficulties when trying to send an AMI action, in my case "QueueStatus".

Code example (sending a "QueueStatus" AMI Action):
```
        # Every AMI Action uses its own event loop
        action_event_loop = asyncio.new_event_loop()

        # Init the Asterisk Manager Interface
        manager: Manager = Manager(loop=action_event_loop, host=host, 
                                   port=port, username=username, secret=secret)

        # Login to the AMI
        try:
            action_event_loop.run_until_complete(manager.connect())
        except OSError:
                raise AMIConnectionError('Can\'t connect to following AMI '
                                         'server: %s' % host)
        # Send the AMI Action
        ami_action_result = action_event_loop.run_until_complete(
            manager.send_action({'Action': 'QueueStatus'}))

        # Create a list with all response sections
        ami_response: List[Message] = []
        if isinstance(ami_action_result, list):
            ami_response = ami_action_result
        else:
            ami_response = [ami_action_result, ]

        # If the command sent has not a successful response log a warning.
        if not ami_response[0].success:
            logger.warning('The following action sent to %s is not '
                            'successful: %s' % (host, self.action_params))

        # Save the AMI Action response and close the AMI connection
        self.response = ami_response
        manager.close()

        # Close the asyncio loop and return the AMI Action response
        action_event_loop.close()
        return self.response
```

In this example the problem is that the AMI Response is incomplete: only a Message (QueueParams) is returned from .send_action() method. Normally this returns a complete list of Message objects with all PBX queues informations.

I checked the source code of Panoramisk but it is not clear to me exactly how the answers are read and parserized with the asyincio socket connection (the end of the AMI Action Response is checked before returning the Message object? If not, can a check that waits for the response end be added?).

I noticed that if I run a time.sleep(0.2) after manager.connect() and then send the AMI action this problem does not occur 70% of the time. I can't understand why.

I thank you in advance for your support and for creating this great library!

**Comment by gawel** [comment]
I have no idea. There is an option to debug the stream received from asterisk. Maybe this can give you a clue. As I remember just use `Manager(stream='path/to/a/file')`

**Comment by oza4h07** [comment]
@Odle98 
Which Asterisk version did you use with above example ?

**Comment by Odle98** [comment]
@gawel @oza4h07 thank you for your answers.
I'll try to find out the problem using the `stream` argument, if I manage to fix the problem I will open a pull request. 

I'm using Asterisk 13.13.1 by the way

**Comment by GMLudo** [comment]
Hi @lorenzocampanile,

I recommend you to run tcpdump or tshark in a screen on port 5038 on Finland and Brazil servers, it might be packet loss or an issue in the TCP queue handling done by Panoramisk.

Or change your architecture to run your daemon locally on the server, if possible

**Comment by lorenzocampanile** [comment]
> Hi @lorenzocampanile,
> 
> I recommend you to run tcpdump or tshark in a screen on port 5038 on Finland and Brazil servers, it might be packet loss or an issue in the TCP queue handling done by Panoramisk.
> 
> Or change your architecture to run your daemon locally on the server, if possible

Hi GMLudo, thank you for your help.

I tried a 2nd time, several months after this issue, and the problem wasn't there anymore (I was lucky).
Maybe the Brazil customer changed something in its office internal network.

At this point I think the problem was some packet loss.
Have a nice day :-)
