### ISSUE TITLE
Listening for Events and Action results simultaneously 

### ISSUE THREAD

**Issue by raj2569** [gawel/panoramisk#91]
Hello,

I am writing a program where I need to listen to events and get the results of actions continuously. Ideally I want to put the events and action results into an `asyncio` queue and process that queue. Been trying to get this working for past two days, but its not yet successful. Here is my current code:

I have an `ActionListener` which continuously `send_action()` and `put()` the result into a queue. Similarly I have an `EventsListener` which pushes all received events to a queue, and finally an `EventsProcess` which fetches items from the queue and processes it.

All these three are run in a main program using `multiprocessing.Process()`

action_listener.py:

```python
import asyncio
import logging

from panoramisk import Manager

class ActionListener:
    def __init__(self, options, queue):
        self.loop = asyncio.get_event_loop()
        self.events_queue = queue

        self.manager = Manager(loop=self.loop, **options)
        self.manager.log.addHandler(logging.NullHandler())

    async def ping(self):
        await self.manager.connect()
        while True:
            message = await self.manager.send_action({'Action': 'ping'})
            print (f"action: putting a message into queue")
            # p = yield from self.manager.send_action({'Action': 'SIPpeers'})                                                                                                       
            await self.events_queue.put(message)
            await asyncio.sleep(5)
        self.manager.close()


    def run(self):
        self.loop.run_until_complete(self.ping())
        self.loop.close()
```
events_listener.py:
```python
import asyncio
import logging

from panoramisk import Manager

class EventsListener:
    def __init__(self, options, queue):
        self.loop = asyncio.get_event_loop()
        self.events_queue = queue

        self.manager = Manager(loop=self.loop, **options)
        self.manager.log.addHandler(logging.NullHandler())
        self.manager.register_event("*", self.handle_events)

    async def handle_events(self, manager, message):
        print (f"events: putting a message into queue")
        await self.events_queue.put(message)

    async def connect(self):
        await self.manager.connect()

    def run(self):
        try:
            self.loop.run_until_complete(self.connect())
            self.loop.run_forever()
        finally:
            self.loop.close()
```

events_process.py:

```python
import asyncio
import logging
from pprint import pprint

class EventsProcess:
    def __init__(self):
        self.loop = asyncio.get_event_loop()
        self.events_queue = asyncio.Queue()

    async def process(self):
        while True:
            message = await self.events_queue.get()
            pprint (message)

    def get_queue(self):
        return self.events_queue

    def run(self):
        self.loop.run_until_complete(self.process())
        self.loop.close()
```
and finally the main program is as follows:

```python
from multiprocessing import Process

from events_listener import EventsListener
from action_listener import ActionListener
from events_process import EventsProcess
def run_events_listener(config, events_queue):
    listener = EventsListener(config["manager"], events_queue)
    listener.run()

def run_action_listener(config, events_queue):
    action = ActionListener(config["manager"], events_queue)
    action.run()

def run_events_process(p):
    p.run()

def main(args=None):
    p = EventsProcess()
    events_queue = p.get_queue()

    p1 = Process(name="erbot_events", target=run_events_listener, args=(config, events_queue,))
    p2 = Process(name="erbot_actions",target=run_action_listener, args=(config,events_queue,))
    p3 = Process(name="erbot_process",target=run_events_process, args=(p,))

    p1.start()
    p2.start()
    p3.start()
```

In the above program, `message = await self.events_queue.get()` do not seems  to be working. No message is being printed, though I can see that putting events does work.

I have removed all unnecessary parts from the program and just posted the bare bones of it. I am sure I am missing some thing with running both action and events together. 

I am sure many too would have similar requirement and a working example of both action and events in tandem would be of much help for some one new to this project.

**Comment by gawel** [comment]
You cant really use multiprocessing with asyncio. You'll lost the event loop. I guess that's your problem.

**Comment by raj2569** [comment]
Is there any best practice or example I can follow to run two instances of panoramisk together (which is assuming, I need two  instances, to run events and action simultaneously) 

I have searched a lot, but there really isn't much out there, and not much guidance in general and  wrt panoramisk specifically.

**Comment by gawel** [comment]
I think there is no benefits to have more than on instance per process since they will use the same event loop. Why an instance is not enough for you ? Is the event loop lagging due to high traffic ?

You can try to use two instance with two event loop (in two different thread). But this is really painfull

**Comment by romkazor** [comment]
> Is there any best practice or example I can follow to run two instances of panoramisk together (which is assuming, I need two instances, to run events and action simultaneously)

Yon dont need two instances of panoramisk if you use one asterisk, if asterisk more than one:

```
import asyncio

from panoramisk.manager import Manager


manager_local = ...
manager_remote = ...


async def ami_local_callback(mngr, msg):
    print(msg)


async def ami_remote_callback(mngr, msg):
    print(msg)


def main():
    manager_local.register_event('*', callback=ami_local_callback)
    manager_remote.register_event('*', callback=ami_remote_callback)
    manager_local.connect()
    manager_remote.connect()

    try:
        manager_local.loop.run_forever()
    except KeyboardInterrupt:
        manager_remote.close()
        manager_local.loop.close()


if __name__ == '__main__':
    main()

**Comment by raj2569** [comment]
> I think there is no benefits to have more than on instance per process since they will use the same event loop. Why an instance is not enough for you ? Is the event loop lagging due to high traffic ?

My requirement is to listen continuously to events from Asterisk, and send an action once every minute and process the result of both. I only have one Asterisk server, and action/response and events has to come from it. 

I could not find a means to do both, simultaneously, in same event loop, which is why I thought of running two event loops. 

From the answers I now understand that single event loop is sufficient for simultaneously listening for events and  sending actions and getting its response. But so far I am unable to figure out how.

**Comment by raj2569** [comment]
> Yon dont need two instances of panoramisk if you use one asterisk

Thanks for the reply, I only have one asterisk, but want both events and actions response from it, continuously. 

Going through the example, I know how to listen to events, and send actions and get response. But could not figure out how to combine both in a single program.

**Comment by romkazor** [comment]
> But could not figure out how to combine both in a single program.
```
@manager.register_event('*')
def callback(manager, message):
    if message.Event == 'FullyBooted':
        response = await manager.send_action({'Action': 'Status'})
        print(response)
    elif message.Event == 'Hangup':
        response = await manager.send_action({'Action': 'Status'})
        print(response)```

**Comment by raj2569** [comment]
> ```
> @manager.register_event('*')
> def callback(manager, message):
>     if message.Event == 'FullyBooted':
>         response = await manager.send_action({'Action': 'Status'})
>         print(response)
>     elif message.Event == 'Hangup':
>         response = await manager.send_action({'Action': 'Status'})
>         print(response)```
> ```

Thanks for this example.

One problem I see with this is that, for firing actions, I need an incoming event like `FullyBooted` or `Hangup` and will not work if I need to send action once every minute (for example). 

One work around I can think of is to send a `Ping` action at the beginning and on receiving the reply send my action, sleep for a minute and then send ping again.

If there are no better way, I can settle for this.

**Comment by romkazor** [comment]
> One problem I see with this is that, for firing actions, I need an incoming event like `FullyBooted` or `Hangup` and will not work if I need to send action once every minute (for example).

you can use aiocron for this and send action every 1,30,60, etc seconds

**Comment by streltsovdenis** [comment]
```
loop_manager = asyncio.new_event_loop()

manager = Manager(
    loop=loop_manager,
    host=HOST,
    port=PORT,
    username=USERNAME,
    secret=SECRET
)


@manager.register_event('*')
def callback(manager, message):
    print(message)


async def ping():
    while True:
        conn = Manager(
            loop=asyncio.get_event_loop(),
            host=HOST,
            port=PORT,
            username=USERNAME,
            secret=SECRET
        )
        await conn.connect()
        response = await conn.send_action({'Action': 'Ping'})
        print(response)
        conn.close()
        await asyncio.sleep(5)


def main():
    manager.connect()
    try:
        loop_manager.create_task(ping())
        manager.loop.run_forever()
    except KeyboardInterrupt:
        manager.loop.close()


if __name__ == '__main__':
    main()
```

**Comment by romkazor** [comment]
Very bad example.

**Comment by raj2569** [comment]
I think I got this correctly. The code works fine, but not sure if there is some non obvious errors.

```python
import asyncio
import logging
from pprint import pprint
from panoramisk import Manager

class EventsListener:
    def __init__(self, options):
        self.loop = asyncio.get_event_loop()
        self.queue = asyncio.Queue()
        self.manager = Manager(loop=self.loop, **options)
        self.manager.log.addHandler(logging.NullHandler())
        self.manager.register_event("*", self.handle_events)

    async def handle_message(self):
        while True:
            message = await self.queue.get()
            pprint (message)
            self.queue.task_done()

    async def handle_actions(self):
        while True:
            response = await self.manager.send_action({'Action': 'Status'})
            self.queue.put_nowait(response)
            await asyncio.sleep(10)

    async def handle_events(self, manager, message):
        event = message.event
        await self.queue.put(event)

    async def connect(self):
        await self.manager.connect()
        t1 = asyncio.create_task(self.handle_message())
        t2 = asyncio.create_task(self.handle_actions())
        await t1
        await t2

    def run(self):
        self.loop.run_until_complete(self.connect())
        self.loop.run_forever()
```

If this is correct, I will make a PR with a clean running example, so that others don't have to waste time reinventing this.

**Comment by gawel** [comment]
I dont really understand why you need a queue with events/responses. It's weird to mix both in the same queue. Also you should try/expept in while True loops to avoid failures.

**Comment by raj2569** [comment]
> I dont really understand why you need a queue with events/responses.

Its easy to process all the events and action responses in a single place. Having an async queue will also let the receive loop of panoramisk run with out any block, as all processing is happening at the other end of the queue. It is bit weird to have two types of messages from the queue, but I find it easier to handle both of them together.

> Also you should try/expept in while True loops to avoid failures.

Yes, this was meant to be a simple example code illustrating the technique.

Shall I raise a PR for including this in `examples/`?

**Comment by gawel** [comment]
Yeah sure. Why not

**Comment by GMLudo** [comment]
Hi @raj2569,

I confirm that you can use the same Panoramisk instance to send actions and receive events.
The only theoretical drawback you might have is that if you have a very long blocking statement in your treatment (CPU or blocking I/O) AND you are very sensitive to execute quickly a piece of code when you receive a specific event, it might be a problem, but I never had this situation from my professional life.

In case of you are in this situation, you might use an external queue, that could be a Redis, PostgreSQL, RabbitMQ or Kafka queue, to have another processes to handle it, but, again, you will increase the complexity of your technical stack.

Based on the content of this issue, the original question seems answered, I'm closing it.
Don't hesitate to re-open in case of extra question.

Have a nice week-end !
