### ISSUE TITLE
Use of "@coroutine" decorator. (deprecated since Python 3.8)

### ISSUE THREAD

**Issue by pbaw** [gawel/panoramisk#94]
Some deprecation warnings poped up. I am using Python 3.8.5.

```
  .../panoramisk/panoramisk/manager.py:102: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def send_awaiting_actions(self, *_):

  .../panoramisk/panoramisk/fast_agi.py:18: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def send_command(self, command):

  ...src/panoramisk/panoramisk/fast_agi.py:53: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def _read_result(self):

  .../panoramisk/panoramisk/fast_agi.py:133: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def handler(self, reader, writer):
```

This programming pattern shows up in the example folder as well. For the manager example and my usecase it _just works™_ to substitute the the decorators to `async def` and `yield from` to `await`.

**Comment by ldo** [comment]
Yeah, that was part of the horrible initial version of `asyncio` that came with Python 3.4. Considering that everything pre-3.6 is now obsolete, I think it’s time to move away from this. This and all the `yield` `from` business.

**Comment by GMLudo** [comment]
@pbaw  and @ldo, your pull requests are welcome to remove that ;-)
